## importing libraries

In [1]:
import numpy as np
import pandas as pd
import os
import math
import timeit
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston
from sklearn.datasets import load_diabetes
import random
os.getcwd()

'C:\\Users\\SHUNVI\\Documents\\PG 2019\\Royal Holloway University of London\\MSc Data Science and Analytics with a year in Industry\\Study Material\\Project\\Codes\\Final Codes'

# Boston Dataset

In [3]:
boston = load_boston()
X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target, random_state = 0)

In [5]:
(np.min(X_train, axis = 0) * 10) * 0.1

array([6.3200e-03, 0.0000e+00, 4.6000e-01, 0.0000e+00, 3.8500e-01,
       3.5610e+00, 2.9000e+00, 1.1742e+00, 1.0000e+00, 1.8700e+02,
       1.2600e+01, 3.2000e-01, 1.7300e+00])

In [6]:
np.ceil(np.min(X_train, axis = 0) * 10) * 0.1

array([1.00e-01, 0.00e+00, 5.00e-01, 0.00e+00, 4.00e-01, 3.60e+00,
       2.90e+00, 1.20e+00, 1.00e+00, 1.87e+02, 1.26e+01, 4.00e-01,
       1.80e+00])

In [4]:
first=np.ceil(np.min(X_train,axis=0)*10)*0.1
first

array([1.00e-01, 0.00e+00, 5.00e-01, 0.00e+00, 4.00e-01, 3.60e+00,
       2.90e+00, 1.20e+00, 1.00e+00, 1.87e+02, 1.26e+01, 4.00e-01,
       1.80e+00])

 ## Decision Stump Regression

In [3]:
class decision_stump_regressor:
    
    def fit(X_train,y_train):
        import timeit
        first=np.ceil(np.min(X_train,axis=0)*10)*0.1
        last=np.ceil(np.max(X_train,axis=0)*10)*0.1

        best_attribute=0
        best_split_pt=0
        best_RSS=math.inf
        best_y_less=0
        best_y_great=0
        y_less=0
        y_great=0
        

        start = timeit.default_timer()
        for i in range(X_train.shape[1]):
            for s in np.arange(first[i],last[i],0.01):
                RSS=0
                y_less=np.nan_to_num(np.sum(y_train[X_train[:,i]<s])/np.sum(X_train[:,i]<s))
                y_great=np.nan_to_num(np.sum(y_train[X_train[:,i]>=s])/np.sum(X_train[:,i]>=s))
                RSS=np.sum((y_train[X_train[:,i]<s]-y_less)**2)+np.sum((y_train[X_train[:,i]>=s]-y_great)**2)
                #if i==9:
                    #print("{} {} {} {}".format(s,y_less,y_great,RSS))
                if RSS<best_RSS:
                    best_attribute=i
                    best_split_pt=s
                    best_RSS=RSS
                    best_y_less=y_less
                    best_y_great=y_great
            #print("{} {}  {}  {}  {}  {}".format(i,data_numpy.feature_names[best_attribute],best_split_pt,best_RSS,best_y_less,best_y_great))     
            #print("{} {}  {}  {}  {}".format(i,best_split_pt,best_RSS,best_y_less,best_y_great)) 
        stop = timeit.default_timer()
        print('fit_Time: ', stop - start) 
        return (best_attribute,best_split_pt,best_y_less,best_y_great)
    def predict(X_train,y_train,X_test):
        import timeit
        best_attribute,best_split_pt,best_y_less,best_y_great=decision_stump_regressor.fit(X_train,y_train) 
        start = timeit.default_timer()
        #print(decision_stump_regressor.fit(X_train,y_train) )
        predict=list(X_test[:,best_attribute]<best_split_pt)
        for i in range(len(predict)):
            if predict[i]==True:
                predict[i]=best_y_less
            else:
                predict[i]=best_y_great
        stop = timeit.default_timer()
        print('predicted_Time: ', stop - start) 
        return np.array(predict)    
    def MSE(X_train,y_train,X_test,y_test):
        best_attribute,best_split_pt,best_y_less,best_y_great=decision_stump_regressor.fit(X_train,y_train) 
        Test_RSS=np.sum((y_test[X_test[:,best_attribute]<best_split_pt]-best_y_less)**2)+np.sum((y_test[X_test[:,best_attribute]>=best_split_pt]-best_y_great)**2)
        return Test_RSS/X_test.shape[0]

In [4]:
decision_stump_regressor.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in double_scalars


fit_Time:  22.778704800000003


(12, 8.100000000000007, 31.158518518518516, 17.87827868852459)

In [5]:
decision_stump_regressor.predict(X_train,y_train,X_test)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in double_scalars


fit_Time:  25.27712110000001
predicted_Time:  0.00015910000000474156


array([31.15851852, 17.87827869, 17.87827869, 17.87827869, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 17.87827869, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 17.87827869, 31.15851852,
       31.15851852, 17.87827869, 31.15851852, 31.15851852, 17.87827869,
       31.15851852, 17.87827869, 17.87827869, 31.15851852, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 31.15851852, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 17.87827869, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 17.87827869, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 17.87827869, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 17.87827869, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 31.15851852, 17.87827869,
       17.87827869, 17.87827869, 17.87827869, 17.87827869, 17.87827869,
       31.15851852, 17.87827869, 31.15851852, 31.15851852, 17.87827869,
       31.15851852, 17.87827869, 17.87827869, 17.87827869, 17.87

In [6]:
decision_stump_regressor.MSE(X_train,y_train,X_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in double_scalars


fit_Time:  23.9360578


58.27672228770273

## Bagging Regression

In [ ]:
def bagging_regressor(X_train,y_train,X_test,B=50,n=int(0.66*(X_train.shape[0]))):
    import timeit

    start1 = timeit.default_timer()



         
    
    prediction=np.zeros((X_test.shape[0],B))
    for i in range(B):
        start = timeit.default_timer()
        bag=list(np.random.choice(X_train.shape[0], n))
        #print(bag)
        boostrap_data=X_train[bag,]
        boostrap_label=y_train[bag]
        prediction[:,i]=decision_stump_regressor.predict(boostrap_data,boostrap_label,X_test) 
        
        stop = timeit.default_timer()

        print('no of trees {} and Time {}: '.format(i,stop - start))
    stop1 = timeit.default_timer()   
    print('total Time {}:' +str(stop1 - start1))
    return np.mean(prediction,axis=1) 

In [11]:
bagging_regressor(X_train,y_train,X_test,B=50,n=int(0.66*(X_train.shape[0])))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in double_scalars


fit_Time:  12.907058800000016
predicted_Time:  0.0001393000000007305
no of trees 0 and Time 12.907984199999987: 
fit_Time:  12.85137229999998
predicted_Time:  0.0001475999999911437
no of trees 1 and Time 12.8519589: 
fit_Time:  12.894866499999978
predicted_Time:  0.00013900000004696267
no of trees 2 and Time 12.895630500000038: 
fit_Time:  13.268202299999984
predicted_Time:  0.0002343999999538937
no of trees 3 and Time 13.269940599999984: 
fit_Time:  14.819020899999998
predicted_Time:  0.00013910000001260414
no of trees 4 and Time 14.821766299999979: 
fit_Time:  13.224546599999996
predicted_Time:  0.00014240000001564113
no of trees 5 and Time 13.225650199999961: 
fit_Time:  12.941203700000017
predicted_Time:  0.0001393000000007305
no of trees 6 and Time 12.941956799999957: 
fit_Time:  12.834415000000035
predicted_Time:  0.00013759999995954786
no of trees 7 and Time 12.835277399999995: 
fit_Time:  12.758288800000003
predicted_Time:  0.000140600000008817
no of trees 8 and Time 12.7592817

array([23.39475301, 21.7404591 , 19.17134951, 18.66136746, 18.66136746,
       21.7404591 , 18.90667658, 21.7404591 , 18.66136746, 19.17134951,
       18.66136746, 19.23549574, 18.66136746, 18.66136746, 34.84700547,
       33.96816642, 19.17134951, 34.36422032, 24.0364278 , 21.7404591 ,
       23.39475301, 18.66136746, 18.66136746, 23.39475301, 19.17134951,
       18.66136746, 18.66136746, 18.66136746, 34.84700547, 18.66136746,
       18.66136746, 18.66136746, 19.17134951, 18.66136746, 21.7404591 ,
       18.66136746, 18.66136746, 21.7404591 , 18.66136746, 18.66136746,
       21.7404591 , 18.66136746, 21.7404591 , 18.66136746, 21.7404591 ,
       21.7404591 , 18.66136746, 18.66136746, 18.66136746, 22.31458737,
       18.66136746, 18.66136746, 18.90667658, 34.84700547, 18.66136746,
       18.66136746, 18.66136746, 18.66136746, 19.6957579 , 18.66136746,
       23.09315573, 18.66136746, 33.96816642, 24.33377852, 18.66136746,
       24.33377852, 19.23549574, 18.66136746, 24.02221422, 19.17

# Diabetes Dataset

In [12]:
diabetes = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(diabetes.data, diabetes.target, random_state = 0)

In [13]:
decision_stump_regressor.fit(X_train,y_train)

fit_Time:  0.033484300000054645


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars


(8, 0.019999999999999934, 121.20982142857143, 216.21495327102804)

In [14]:
decision_stump_regressor.predict(X_train,y_train,X_test)

fit_Time:  0.04306319999977859
predicted_Time:  0.00013440000020636944


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars


array([121.20982143, 216.21495327, 121.20982143, 121.20982143,
       121.20982143, 216.21495327, 121.20982143, 216.21495327,
       121.20982143, 216.21495327, 216.21495327, 121.20982143,
       121.20982143, 121.20982143, 216.21495327, 121.20982143,
       121.20982143, 121.20982143, 121.20982143, 121.20982143,
       121.20982143, 121.20982143, 216.21495327, 121.20982143,
       216.21495327, 216.21495327, 121.20982143, 121.20982143,
       216.21495327, 121.20982143, 216.21495327, 121.20982143,
       121.20982143, 121.20982143, 216.21495327, 121.20982143,
       121.20982143, 121.20982143, 121.20982143, 216.21495327,
       121.20982143, 216.21495327, 216.21495327, 216.21495327,
       121.20982143, 121.20982143, 121.20982143, 121.20982143,
       121.20982143, 216.21495327, 121.20982143, 121.20982143,
       121.20982143, 216.21495327, 216.21495327, 216.21495327,
       216.21495327, 121.20982143, 121.20982143, 216.21495327,
       216.21495327, 121.20982143, 121.20982143, 121.20

In [15]:
decision_stump_regressor.MSE(X_train,y_train,X_test,y_test)

fit_Time:  0.04875510000010763


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars


4558.579456710617

In [16]:
bagging_regressor(X_train,y_train,X_test,B=50,n=int(0.66*(X_train.shape[0])))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars


fit_Time:  0.03390289999970264
predicted_Time:  0.0001366999999845575
no of trees 0 and Time 0.034645499999896856: 
fit_Time:  0.03293200000007346
predicted_Time:  0.00011919999997189734
no of trees 1 and Time 0.03424880000011399: 
fit_Time:  0.02455260000033377
predicted_Time:  0.00012240000023666653
no of trees 2 and Time 0.02521679999972548: 
fit_Time:  0.024261900000055903
predicted_Time:  0.00011680000034175464
no of trees 3 and Time 0.0247681000000739: 
fit_Time:  0.025905999999849882
predicted_Time:  0.00011769999991884106
no of trees 4 and Time 0.02633449999984805: 
fit_Time:  0.02627859999984139
predicted_Time:  0.00012030000016238773
no of trees 5 and Time 0.026729600000180653: 
fit_Time:  0.02545349999991231
predicted_Time:  0.00012019999985568575
no of trees 6 and Time 0.026039899999886984: 
fit_Time:  0.025025700000242068
predicted_Time:  0.00011770000037358841
no of trees 7 and Time 0.02541139999993902: 
fit_Time:  0.025442199999815784
predicted_Time:  0.00011519999998199

array([167.64830576, 213.64885534, 131.5227705 , 114.28085526,
       150.24697202, 213.64885534, 114.28085526, 213.64885534,
       150.24697202, 213.64885534, 177.68273858, 167.64830576,
       114.28085526, 114.28085526, 211.78166963, 114.28085526,
       131.682189  , 114.28085526, 114.28085526, 150.24697202,
       150.24697202, 167.26879397, 175.81555286, 150.24697202,
       213.64885534, 211.57178959, 114.28085526, 114.28085526,
       193.05746811, 167.64830576, 175.81555286, 114.28085526,
       114.28085526, 131.682189  , 177.68273858, 169.34585972,
       133.37974296, 133.37974296, 131.5227705 , 213.64885534,
       114.28085526, 175.81555286, 177.68273858, 177.68273858,
       150.24697202, 114.28085526, 133.37974296, 150.24697202,
       133.37974296, 211.78166963, 131.682189  , 114.28085526,
       148.16990627, 175.81555286, 213.64885534, 177.68273858,
       213.64885534, 114.28085526, 114.28085526, 211.57178959,
       213.64885534, 150.24697202, 150.24697202, 114.28