## importing libraries

In [1]:
import numpy as np
import pandas as pd
import os
import math
import timeit
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.datasets import load_wine
from sklearn.datasets import load_digits
from sklearn.datasets import load_breast_cancer
import random
os.getcwd()

'C:\\Users\\SHUNVI\\Documents\\PG 2019\\Royal Holloway University of London\\MSc Data Science and Analytics with a year in Industry\\Study Material\\Project\\Codes\\Final Codes'

## Decision Stump Classification

In [2]:
class decision_stump_classifier:
    def fit(X_train,y_train):
        class_less=0
        class_great=0
        best_attribute=0
        best_split_pt=0
        best_pmk=-math.inf
        first=np.ceil(np.min(X_train,axis=0)*10)*0.1
        last=np.ceil(np.max(X_train,axis=0)*10)*0.1
        for i in range(X_train.shape[1]):
            for s in np.arange(first[i],last[i],1):
                unique, counts = np.unique(y_train[X_train[:,i]<s], return_counts=True)
                r1=dict(zip(unique, counts))
                if len(r1)==0:
                    r1.update({0:0}) 
                max1=max(r1.values())
                #sum(dict(zip(unique, counts)).values())
                #if i==1:
                #print(r1,s,max1)

                unique, counts = np.unique(y_train[X_train[:,i]>=s], return_counts=True)
                r2=dict(zip(unique, counts))
                if len(r2)==0:
                    r2.update({0:0}) 
                max2=max(r2.values())
                #sum(dict(zip(unique, counts)).values())
                #if i==1:
                #print(r2,s,max2)
                pmk=max(max1,max2)
                #print(pmk)
                if pmk>=best_pmk:
                    best_attribute=i
                    best_split_pt=s
                    best_pmk=pmk
                    best_r1=r1
                    best_r2=r2 
                    class_less=list(best_r1.values()).index(max(best_r1.values()))                 
                    class_great=list(best_r2.values()).index(max(best_r2.values())) 
        #print("  {} {}  {} {} {} {} {}".format(best_r1,best_r2,class_less,class_great,best_attribute,best_split_pt,best_pmk))
        return (class_less,class_great,best_attribute,best_split_pt)
        
     
    def predict(X_train,y_train,X_test):   
        class_less,class_great,best_attribute,best_split_pt=decision_stump_classifier.fit(X_train,y_train) 
        predict=list(X_test[:,best_attribute]<best_split_pt)
        
        for i in range(len(predict)):
            if predict[i]==True:
                predict[i]=class_less
            else:
                predict[i]=class_great
        return np.array(predict) 
    
    def error_rate(y_test):
        predict=decision_stump_classifier.predict(X_train,y_train,X_test)
        return np.sum(predict==y_test)/len(y_test)

#  Iris Dataset

In [3]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state = 0)

In [4]:
np.unique(iris.target)

array([0, 1, 2])

In [5]:
decision_stump_classifier.fit(X_train,y_train)

(0, 1, 3, 1.1)

In [6]:
decision_stump_classifier.predict(X_train,y_train,X_test)

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1])

In [7]:
decision_stump_classifier.error_rate(y_test)

0.7105263157894737

In [61]:
X_test[:,0]

array([5.8, 6. , 5.5, 7.3, 5. , 6.3, 5. , 6.7, 6.8, 6.1, 6.1, 6.4, 6.1,
       6.5, 6.1, 4.9, 6. , 5.5, 4.8, 5.4, 5.6, 5.6, 4.8, 4.4, 6.2, 4.6,
       5.1, 6.2, 5. , 5. , 6.4, 5.4, 5.2, 6.1, 6.4, 5.2, 5.7, 6. ])

## Bagging Classification

In [10]:
def bagging_classifier(X_train,X_test,y_train,B=5,n=int(0.66*(X_train.shape[0]))):
    
    
    prediction=np.ones((X_test.shape[0],B))*5
    for i in range(B):
        bag=list(np.random.choice(X_train.shape[0], n))
        #print(bag)
        boostrap_data=X_train[bag,]
        boostrap_label=y_train[bag]
        decision_stump_classifier.fit(boostrap_data,boostrap_label)
        print(decision_stump_classifier.fit(boostrap_data,boostrap_label) )
        prediction[:,i]=decision_stump_classifier.predict(boostrap_data,boostrap_label,X_test) 
        #print(prediction)
    mode_prediction=np.zeros(X_test.shape[0])
    for i in range(prediction.shape[0]):
        unique, counts = np.unique(prediction[i,:], return_counts=True)
        nn=dict(zip(unique, counts))
        mode_prediction[i]=list(nn.values()).index(max(nn.values()))    
    return mode_prediction    

In [11]:
bagging_classifier(X_train,X_test,y_train,B=1,n=int(0.66*(X_train.shape[0])))

(0, 0, 3, 2.1)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

# Wine Dataset

In [12]:
wine =  load_wine()
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, random_state = 0)

In [13]:
decision_stump_classifier.fit(X_train,y_train)  

(1, 0, 12, 1546.0)

In [14]:
decision_stump_classifier.predict(X_train,y_train,X_test)  

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [15]:
decision_stump_classifier.error_rate(y_test)

0.4888888888888889

In [16]:
bagging_classifier(X_train,X_test,y_train,B=10,n=int(0.66*(X_train.shape[0])))

(2, 0, 12, 1514.0)
(0, 0, 12, 770.0)
(1, 0, 12, 1509.0)
(1, 0, 12, 1509.0)
(1, 0, 12, 1514.0)
(1, 0, 12, 1546.0)
(1, 0, 12, 1514.0)
(1, 0, 12, 1546.0)
(1, 0, 12, 1514.0)
(1, 0, 12, 1514.0)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Breast Cancer Dataset

In [17]:
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, random_state = 0)

In [18]:
decision_stump_classifier.fit(X_train,y_train)  

(0, 1, 27, 0.0)

In [19]:
decision_stump_classifier.predict(X_train,y_train,X_test)  

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
decision_stump_classifier.error_rate(y_test)

0.6293706293706294

In [55]:
bagging_classifier(X_train,X_test,y_train,B=10,n=int(0.66*(X_train.shape[0])))

(0, 1, 27, 0.0)
(0, 1, 27, 0.0)
(0, 1, 27, 0.0)
(0, 1, 27, 0.0)
(0, 1, 27, 0.0)
(0, 1, 27, 0.0)
(0, 1, 27, 0.0)
(0, 1, 27, 0.0)
(0, 1, 27, 0.0)
(0, 1, 27, 0.0)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])