## importing libraries

In [1]:
import numpy as np
import pandas as pd
import os
import math
import timeit
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.datasets import load_wine
from sklearn.datasets import load_digits
import random
os.getcwd()

'C:\\Users\\SHUNVI\\Documents\\PG 2019\\Royal Holloway University of London\\MSc Data Science and Analytics with a year in Industry\\Study Material\\Project\\Codes\\Final Codes'

## Decision Stump Classification

In [2]:
class decision_stump_classifier:
    
    def fit(X_train,y_train):
        first=np.ceil(np.min(X_train,axis=0)*10)*0.1
        last=np.ceil(np.max(X_train,axis=0)*10)*0.1
        
        class_less=0
        class_great=0
        best_attribute=0
        best_split_pt=0
        best_pmk=-math.inf
        
        for i in range(X_train.shape[1]):
            for s in np.arange(first[i],last[i],1):
                unique, counts = np.unique(y_train[X_train[:,i]<s], return_counts=True)
                r1=dict(zip(unique, counts))
                if len(r1)==0:
                    r1.update({0:0}) 
                max1=max(r1.values())
                #sum(dict(zip(unique, counts)).values())
                #if i==1:
                #print(r1,s,max1)

                unique, counts = np.unique(y_train[X_train[:,i]>=s], return_counts=True)
                r2=dict(zip(unique, counts))
                if len(r2)==0:
                    r2.update({0:0}) 
                max2=max(r2.values())
                #sum(dict(zip(unique, counts)).values())
                #if i==1:
                #print(r2,s,max2)
                pmk=max(max1,max2)
                #print(pmk)
                if pmk>=best_pmk:
                    best_attribute=i
                    best_split_pt=s
                    best_pmk=pmk
                    best_r1=r1
                    best_r2=r2 
                    class_less=list(best_r1.values()).index(max(best_r1.values()))                 
                    class_great=list(best_r2.values()).index(max(best_r2.values())) 
        #print("  {} {}  {} {} {} {} {}".format(best_r1,best_r2,class_less,class_great,best_attribute,best_split_pt,best_pmk))
        return (class_less,class_great,best_attribute,best_split_pt)
        
     
    def predict(X_train,y_train,X_test):   
        class_less,class_great,best_attribute,best_split_pt=decision_stump_classifier.fit(X_train,y_train) 
        predict=list(X_test[:,best_attribute]<best_split_pt)
        
        for i in range(len(predict)):
            if predict[i]==True:
                predict[i]=class_less
            else:
                predict[i]=class_great
        return np.array(predict) 
    
    def error_rate(y_test):
        predict=decision_stump_classifier.predict(X_train,y_train,X_test)
        return np.sum(predict==y_test)/len(y_test)
                
                
#decision_stump_classifier.fit(X_train,y_train)  
#decision_stump_classifier.predict(X_train,y_train,X_test)  
#decision_stump_classifier.error_rate(y_test)

In [3]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state = 0)

In [4]:
decision_stump_classifier.fit(X_train,y_train)  

(0, 1, 3, 1.1)

In [5]:
decision_stump_classifier.predict(X_train,y_train,X_test)  

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1])

In [6]:
decision_stump_classifier.error_rate(y_test)

0.7105263157894737

In [9]:
wine =  load_wine()
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, random_state = 0)

In [10]:
decision_stump_classifier.fit(X_train,y_train)  

(1, 0, 12, 1546.0)

In [11]:
decision_stump_classifier.predict(X_train,y_train,X_test)  

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [12]:
decision_stump_classifier.error_rate(y_test)

0.4888888888888889

In [14]:
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state = 0)

In [15]:
decision_stump_classifier.fit(X_train,y_train)  

(0, 1, 3, 1.1)

In [16]:
decision_stump_classifier.predict(X_train,y_train,X_test)  

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1])

In [17]:
decision_stump_classifier.error_rate(y_test)

0.7105263157894737